apiVersion: v1
kind: Namespace
metadata:
  name: kubecost
  labels:
    goldilocks.fairwinds.com/enabled: "false"
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: v1
kind: Namespace
metadata:
  name: goldilocks
---
apiVersion: v1
kind: Namespace
metadata:
  name: default
  labels:
    goldilocks.fairwinds.com/enabled: "true"
